# Generated by Django 3.1.12 on 2024-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leche',
            fields=[
                ('leche_id', models.AutoField(primary_key=True, serialize=False)),
                ('litros_leche', models.IntegerField()),
                ('fecha_leche', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagas',
            fields=[
                ('paga_id', models.AutoField(primary_key=True, serialize=False)),
                ('litros_paga', models.IntegerField()),
                ('fecha_paga', models.DateTimeField()),
                ('monto_paga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=150)),
                ('prod_email', models.EmailField(max_length=254)),
                ('prod_phone', models.CharField(max_length=15)),
                ('prod_password', models.CharField(max_length=20)),
                ('prod_address', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_name', models.CharField(max_length=150)),
                ('prov_email', models.EmailField(max_length=254)),
                ('prov_phone', models.CharField(max_length=15)),
                ('prov_city', models.CharField(max_length=30)),
                ('prov_street', models.CharField(max_length=30)),
                ('prov_number', models.IntegerField()),
                ('prov_pluscode', models.CharField(max_length=20)),
            ],
        ),
    ]
